---
deployment:
  tasks:
    - export BACKENDPATH=/home/trusteracademy/back.trusterlabsacademy
    - /usr/bin/rsync -av --exclude='.env' --exclude='db.sqlite3' --exclude='__pycache__' --exclude='venv' --exclude='.git' CMS/ $BACKENDPATH/
