# Generated by Django 5.0.6 on 2026-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0003_staffmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text="e.g., 'welcome_email', 'password_reset_email'", max_length=255, unique=True)),
                ('subject', models.CharField(default='Notification from TrusterLab', max_length=255)),
                ('html_content', models.TextField(help_text='HTML content of the email.')),
                ('text_content', models.TextField(blank=True, help_text='Plain text fallback (optional).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
