# Generated by Django 5.0.6 on 2026-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0005_sitevisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='navbar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logos/'),
        ),
    ]
