# Generated by Django 5.0.6 on 2026-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0006_sitesetting_navbar_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Direct link to photo (e.g., Google Drive)', max_length=1000, null=True),
        ),
    ]
