# Generated by Django 5.0.6 on 2026-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0007_staffmember_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='top_announcements',
            field=models.TextField(blank=True, help_text='Enter announcements separated by new lines', null=True),
        ),
    ]
