# Generated by Django 5.0.6 on 2026-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0008_sitesetting_top_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
