# Generated by Django 5.0.6 on 2026-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0009_partner_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Direct link to photo (e.g., Cloudinary)', max_length=1000, null=True),
        ),
    ]
