# Generated by Django 5.0.6 on 2026-07-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0010_alter_staffmember_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
