# Generated by Django 5.0.6 on 2026-08-05 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0013_sitesetting_youtube_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', '-created_at'], name='SuperSettin_is_read_5c3176_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitor',
            index=models.Index(fields=['ip_address', 'visited_date', 'path'], name='SuperSettin_ip_addr_035b63_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitor',
            index=models.Index(fields=['-created_at'], name='SuperSettin_created_9e40c0_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-created_at', 'user'], name='SuperSettin_created_0e94c8_idx'),
        ),
    ]
