# Generated by Django 5.0.6 on 2026-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0016_sitesetting_external_finance_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allow_professional_membership',
            field=models.BooleanField(default=True, help_text='Toggle to allow or disable Professional Membership applications'),
        ),
    ]
