# Generated by Django 5.0.6 on 2026-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperSetting', '0017_sitesetting_allow_professional_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='allow_enterprise_membership',
            field=models.BooleanField(default=True, help_text='Toggle to allow or disable Enterprise Membership applications'),
        ),
    ]
