export const adminConfig = {
  learners: {
    label: 'Learners',
    endpoint: '/auth/api/learners/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'full_name', label: 'Name' },
      { field: 'email', label: 'Email' },
      { field: 'phone_number', label: 'Phone' },
    ],
    canCreate: false,
    canEdit: false,
    canDelete: true,
  },
  instructors: {
    label: 'Instructors',
    endpoint: '/auth/api/instructors/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'full_name', label: 'Name' },
      { field: 'email', label: 'Email' },
      { field: 'phone_number', label: 'Phone' },
      { field: 'specialization', label: 'Specialization' },
      { field: 'is_approved', label: 'Approved' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  courses: {
    label: 'Courses',
    endpoint: '/api/courses/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'difficulty', label: 'Difficulty' },
      { field: 'course_status', label: 'Status' },
      { field: 'is_locked', label: 'Locked' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  modules: {
    label: 'Modules',
    endpoint: '/api/modules/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'order', label: 'Order' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  lessons: {
    label: 'Lessons',
    endpoint: '/api/lessons/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'lesson_type', label: 'Type' },
      { field: 'is_published', label: 'Published' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  quizzes: {
    label: 'Quizzes / Exams',
    endpoint: '/api/quizes/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'max_attempts', label: 'Max Attempts' },
      { field: 'is_published', label: 'Published' },
      { field: 'is_locked', label: 'Locked' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  quiz_questions: {
    label: 'Quiz Questions',
    endpoint: '/api/quiz_questions/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'quiz', label: 'Quiz ID' },
      { field: 'question_text', label: 'Question' },
      { field: 'correct_option', label: 'Correct Answer' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  enquiries: {
    label: 'Student Enquiries',
    endpoint: '/enquiry/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'user_name', label: 'User' },
      { field: 'email', label: 'Email' },
      { field: 'course_title', label: 'Course' },
      { field: 'status', label: 'Status' },
    ],
    canCreate: false,
    canEdit: false,
    canDelete: true,
    customActions: [
      {
        label: 'Enroll',
        actionType: 'api',
        apiEndpoint: (id) => `/enquiry/${id}/enroll_student/`,
        method: 'POST',
        showIf: (item) => item.status === 'pending'
      }
    ]
  },
  trainings: {
    label: 'Training Sessions',
    endpoint: '/training/trainings/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'starting_date', label: 'Start Date' },
      { field: 'ending_date', label: 'End Date' },
      { field: 'max_participants', label: 'Max Seats' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  classwork: {
    label: 'Training Classworks',
    endpoint: '/training/classwork/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'training', label: 'Training ID' },
      { field: 'due_date', label: 'Due Date' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  exams: {
    label: 'Training Exams',
    endpoint: '/training/exams/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'training', label: 'Training ID' },
      { field: 'exam_date', label: 'Date' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  partners: {
    label: 'Partners',
    endpoint: '/settings/partners/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'name', label: 'Name' },
      { field: 'is_active', label: 'Active' },
      { field: 'created_at', label: 'Created At' },
    ],
    formFields: [
      { field: 'name', label: 'Partner Name', type: 'text' },
      { field: 'logo', label: 'Partner Logo', type: 'image' },
      { field: 'website_url', label: 'Website URL', type: 'text' },
      { field: 'is_active', label: 'Is Active', type: 'boolean' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  contact_messages: {
    label: 'Contact Messages',
    endpoint: '/settings/contact-messages/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'name', label: 'Sender Name' },
      { field: 'email', label: 'Email' },
      { field: 'subject', label: 'Subject' },
      { field: 'is_read', label: 'Read Status' },
    ],
    canCreate: false,
    canEdit: true,
    canDelete: true,
  },
  system_logs: {
    label: 'System Logs',
    endpoint: '/settings/system-logs/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'user_name', label: 'User' },
      { field: 'action', label: 'Action' },
      { field: 'details', label: 'Details' },
      { field: 'ip_address', label: 'IP Address' },
      { field: 'created_at', label: 'Timestamp' },
    ],
    canCreate: false,
    canEdit: false,
    canDelete: false,
  },
  site_settings: {
    label: 'Global Site Settings',
    endpoint: '/settings/site-settings/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'company_name', label: 'Company' },
      { field: 'contact_email', label: 'Email' },
      { field: 'contact_phone', label: 'Phone' },
    ],
    formFields: [
      { field: 'company_name', label: 'Company Name', type: 'text' },
      { field: 'contact_email', label: 'Contact Email', type: 'email' },
      { field: 'contact_phone', label: 'Contact Phone', type: 'text' },
      { field: 'location_address', label: 'Physical Address', type: 'textarea' },
      { field: 'facebook_url', label: 'Facebook URL', type: 'url' },
      { field: 'twitter_url', label: 'Twitter URL', type: 'url' },
      { field: 'linkedin_url', label: 'LinkedIn URL', type: 'url' },
    ],
    canCreate: false,
    canEdit: true,
    canDelete: false,
  },
  staff_members: {
    label: 'Staff Members',
    endpoint: '/settings/staff-members/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'name', label: 'Name' },
      { field: 'position', label: 'Position' },
      { field: 'is_active', label: 'Active' },
    ],
    formFields: [
      { field: 'name', label: 'Name', type: 'text' },
      { field: 'position', label: 'Position', type: 'text' },
      { field: 'photo', label: 'Photo', type: 'image' },
      { field: 'bio', label: 'Bio', type: 'textarea' },
      { field: 'is_active', label: 'Is Active', type: 'boolean' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  research_publications: {
    label: 'Research Publications',
    endpoint: '/api/research/publications/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'authors', label: 'Authors' },
      { field: 'publication_date', label: 'Date' },
      { field: 'is_published', label: 'Published' },
    ],
    formFields: [
      { field: 'title', label: 'Title', type: 'text' },
      { field: 'authors', label: 'Authors', type: 'text' },
      { field: 'publication_date', label: 'Publication Date', type: 'date' },
      { field: 'abstract', label: 'Abstract', type: 'textarea' },
      { field: 'content', label: 'Content', type: 'textarea' },
      { field: 'document', label: 'Document (PDF)', type: 'file' },
      { field: 'image', label: 'Featured Image', type: 'image' },
      { field: 'is_published', label: 'Is Published', type: 'boolean' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  webinars: {
    label: 'Webinars',
    endpoint: '/api/research/webinars/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'title', label: 'Title' },
      { field: 'date_time', label: 'Date & Time' },
      { field: 'status', label: 'Status' },
    ],
    formFields: [
      { field: 'title', label: 'Title', type: 'text' },
      { field: 'description', label: 'Description', type: 'textarea' },
      { field: 'date_time', label: 'Date/Time', type: 'datetime-local' },
      { field: 'meeting_link', label: 'Meeting Link', type: 'url' },
      { field: 'thumbnail', label: 'Thumbnail', type: 'file' },
      { field: 'thumbnail_url', label: 'Thumbnail URL', type: 'url' },
      { field: 'status', label: 'Status', type: 'select', options: [
        { value: 'UPCOMING', label: 'Upcoming' },
        { value: 'COMPLETED', label: 'Completed' },
        { value: 'CANCELLED', label: 'Cancelled' },
      ] },
      { field: 'decisions_summary', label: 'Decisions/Summary', type: 'textarea' },
      { field: 'requires_membership_id', label: 'Requires Membership ID', type: 'boolean' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
  },
  webinar_registrations: {
    label: 'Webinar Registrations',
    endpoint: '/api/research/registrations/',
    columns: [
      { field: 'id', label: 'ID' },
      { field: 'full_name', label: 'Name' },
      { field: 'email', label: 'Email' },
      { field: 'attended', label: 'Attended' },
    ],
    formFields: [
      { field: 'full_name', label: 'Full Name', type: 'text' },
      { field: 'email', label: 'Email', type: 'email' },
      { field: 'phone_number', label: 'Phone', type: 'text' },
      { field: 'membership_id', label: 'Membership ID', type: 'text' },
      { field: 'attended', label: 'Attended', type: 'boolean' },
    ],
    canCreate: false,
    canEdit: true,
    canDelete: true,
  },
  memberships: {
    label: 'Memberships',
    endpoint: '/api/membership/memberships/',
    columns: [
      { field: 'MembershipID', label: 'ID' },
      { field: 'Fullname', label: 'Name' },
      { field: 'email', label: 'Email' },
      { field: 'phone_number', label: 'Phone' },
    ],
    formFields: [
      { field: 'Fullname', label: 'Full Name', type: 'text' },
      { field: 'email', label: 'Email', type: 'email' },
      { field: 'phone_number', label: 'Phone', type: 'text' },
      { field: 'Where_heard_about_us', label: 'Source', type: 'text' },
      { field: 'duration_days', label: 'Duration (Days)', type: 'number' },
      { field: 'description', label: 'Description', type: 'textarea' },
    ],
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkUpload: true,
  }
};
