# Generated by Django 5.0.6 on 2026-07-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='can_create_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_delete_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_update_courses',
            field=models.BooleanField(default=True),
        ),
    ]
