# Generated by Django 5.0.6 on 2026-07-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_instructor_can_create_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='can_approve_certificates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_manage_trainings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_view_students',
            field=models.BooleanField(default=True),
        ),
    ]
