# Generated by Django 5.0.6 on 2026-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_instructor_can_approve_certificates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='can_approve_certificates',
            new_name='can_create_certificates',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='can_manage_trainings',
            new_name='can_create_trainings',
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_delete_certificates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_delete_trainings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_update_certificates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='can_update_trainings',
            field=models.BooleanField(default=True),
        ),
    ]
