# Generated by Django 5.0.6 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_rename_can_approve_certificates_instructor_can_create_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Direct link to profile picture (e.g., Google Drive)', max_length=1000, null=True),
        ),
    ]
