# Generated by Django 5.0.6 on 2026-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_instructor_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Direct link to profile picture (e.g., Cloudinary)', max_length=1000, null=True),
        ),
    ]
