# Generated by Django 5.0.6 on 2026-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_instructor_profile_picture_url'),
        ('Course', '0016_quizsubmission_training_classwork_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('learner', 'Learner'), ('instructor', 'Instructor'), ('admin', 'Admin')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['-created_at'], name='Auth_instru_created_b20f82_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['is_approved'], name='Auth_instru_is_appr_255ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='learner',
            index=models.Index(fields=['-created_at'], name='Auth_learne_created_50d7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='Auth_user_user_ty_604d46_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='Auth_user_date_jo_d2a671_idx'),
        ),
    ]
