# Generated by Django 5.0.6 on 2026-07-07 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requrement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
