# Generated by Django 5.0.6 on 2026-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0003_requrement_name_alter_requrement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requrement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
