# Generated by Django 5.0.6 on 2026-07-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_courseresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exams', to='Course.course'),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='Course.lesson'),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='Course.module'),
        ),
    ]
