# Generated by Django 5.0.6 on 2026-07-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_lesson_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('unpublished', 'Unpublished')], default='draft', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If true, the course content is locked and cannot be accessed by learners.'),
        ),
    ]
