# Generated by Django 5.0.6 on 2026-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_remove_course_is_published_course_course_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If false, the quiz/exam will not be visible to learners.'),
        ),
    ]
