# Generated by Django 5.0.6 on 2026-07-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_instructor_can_create_courses_and_more'),
        ('Course', '0006_quizes_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='marks',
            field=models.PositiveIntegerField(default=1, help_text='Marks awarded for this question'),
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('answers_data', models.JSONField(blank=True, help_text='Stored answers submitted by the learner', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to='Auth.learner')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Course.quizes')),
            ],
            options={
                'verbose_name': 'Quiz Submission',
                'verbose_name_plural': 'Quiz Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
