# Generated by Django 5.0.6 on 2026-07-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_quizquestion_marks_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='auto_issue_certificate',
            field=models.BooleanField(default=False, help_text='If true, certificates are issued automatically upon completion. Otherwise, wait for Admin/Instructor to issue manually.'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False, help_text='If true, learners will receive a certificate upon completion.'),
        ),
    ]
