# Generated by Django 5.0.6 on 2026-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_course_auto_issue_certificate_course_has_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final grade/Score object', max_digits=5),
        ),
    ]
