# Generated by Django 5.0.6 on 2026-07-14 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_rename_can_approve_certificates_instructor_can_create_certificates_and_more'),
        ('Course', '0009_alter_enrollment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Course'), ('module', 'Module'), ('lesson', 'Lesson'), ('training', 'Training'), ('classwork', 'Training Classwork'), ('exam', 'Training Exam')], max_length=50)),
                ('object_id', models.IntegerField(help_text='ID of the entity being requested')),
                ('destination_id', models.IntegerField(blank=True, help_text='ID of the destination course, module, or training', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reuse_requests_received', to='Auth.instructor')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuse_requests_made', to='Auth.instructor')),
            ],
            options={
                'verbose_name': 'Reuse Request',
                'verbose_name_plural': 'Reuse Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
