# Generated by Django 5.0.6 on 2026-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_reuserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_description',
            field=models.TextField(blank=True, help_text="e.g., 'This workshop covered SSL/TLS fundamentals...'", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_duration',
            field=models.CharField(blank=True, help_text="e.g., '1.5-Hour'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_program_title',
            field=models.CharField(blank=True, help_text="e.g., 'SSL/TLS: Securing Communication on the Internet'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_type_text',
            field=models.CharField(blank=True, help_text="e.g., 'Online Cybersecurity Workshop'", max_length=100, null=True),
        ),
    ]
