# Generated by Django 5.0.6 on 2026-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_course_certificate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='pass_mark',
            field=models.PositiveIntegerField(default=70, help_text='Percentage required to pass (e.g., 70 for 70%)'),
        ),
    ]
