# Generated by Django 5.0.6 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_quizes_pass_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Direct link to course thumbnail (e.g., Google Drive)', max_length=1000, null=True),
        ),
    ]
