# Generated by Django 5.0.6 on 2026-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0013_course_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Direct link to course thumbnail (e.g., Cloudinary)', max_length=1000, null=True),
        ),
    ]
