# Generated by Django 5.0.6 on 2026-08-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0014_alter_course_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='matching_pairs',
            field=models.JSONField(blank=True, help_text="Stored as [{'id': 1, 'left': '...', 'right': '...'}, ...]", null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('MATCHING', 'Matching')], default='MULTIPLE_CHOICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
