# Generated by Django 5.0.6 on 2026-08-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0015_quizquestion_matching_pairs_and_more'),
        ('Training', '0013_trainingfinalexamsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='training_classwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Training.trainingclasswork'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='training_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Training.trainingfinalexam'),
        ),
    ]
