# Generated by Django 5.0.6 on 2026-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_user_options_alter_user_user_type_and_more'),
        ('Course', '0016_quizsubmission_training_classwork_and_more'),
        ('Training', '0016_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_status', '-created_at'], name='Course_cour_course__52bddf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'course_status'], name='Course_cour_instruc_76bedf_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['learner', 'status'], name='Course_enro_learner_dac48a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='Course_enro_course__667017_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['-enrolled_at'], name='Course_enro_enrolle_e225f5_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['learner', 'is_completed'], name='Course_less_learner_da5b36_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'is_completed'], name='Course_less_lesson__f6fac2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['learner', 'quiz'], name='Course_quiz_learner_c0a842_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['-submitted_at'], name='Course_quiz_submitt_8f70fa_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['training_classwork'], name='Course_quiz_trainin_832d85_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['training_exam'], name='Course_quiz_trainin_f11908_idx'),
        ),
    ]
