# Generated by Django 5.0.6 on 2026-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_user_options_alter_user_user_type_and_more'),
        ('Course', '0017_course_course_cour_course__52bddf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Cybersecurity', 'Cybersecurity'), ('Networking', 'Networking'), ('Programming', 'Programming'), ('Cloud Computing', 'Cloud Computing'), ('AI & Data Science', 'AI & Data Science'), ('Other', 'Other')], db_index=True, default='Cybersecurity', max_length=50),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'course_status'], name='Course_cour_categor_122066_idx'),
        ),
    ]
