# Generated by Django 5.0.6 on 2026-08-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0018_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='module_thumbnails/'),
        ),
        migrations.AddField(
            model_name='module',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Direct link to module thumbnail (e.g., Cloudinary)', max_length=1000, null=True),
        ),
    ]
