# Generated by Django 5.0.6 on 2026-07-02 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paypal_payment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('approved', 'Approved'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
