# Generated by Django 5.0.6 on 2026-09-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0002_membership_expiry_date_membership_membership_type_and_more'),
        ('payment', '0002_payment_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Membership.membership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('course', 'Course'), ('membership', 'Membership')], default='course', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
    ]
