# Generated by Django 5.0.6 on 2026-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpublication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research_images/'),
        ),
    ]
