# Generated by Django 5.0.6 on 2026-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_researchpublication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a photo thumbnail', null=True, upload_to='webinar_thumbnails/'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Or paste a link to an image', null=True),
        ),
    ]
