# Generated by Django 5.0.6 on 2026-07-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0003_webinar_thumbnail_webinar_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='requires_membership_id',
            field=models.BooleanField(default=False, help_text='Require users to provide a valid Membership ID to register'),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='membership_id',
            field=models.CharField(blank=True, help_text='Membership ID used for registration', max_length=100, null=True),
        ),
    ]
