# Generated by Django 5.0.6 on 2026-07-13 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0003_instructor_can_create_courses_and_more'),
        ('Course', '0008_course_auto_issue_certificate_course_has_certificate'),
        ('Training', '0008_training_auto_issue_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_issued', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='Course.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='Auth.learner')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='Training.training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
