# Generated by Django 5.0.6 on 2026-07-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
