# Generated by Django 5.0.6 on 2026-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_user_options_alter_user_user_type_and_more'),
        ('Course', '0017_course_course_cour_course__52bddf_idx_and_more'),
        ('Training', '0016_alter_training_options_and_more'),
        ('certification', '0002_certificate_certificate_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['learner', 'is_issued'], name='certificati_learner_94611f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['course', 'is_issued'], name='certificati_course__ee23b0_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['training', 'is_issued'], name='certificati_trainin_aa8b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['-created_at'], name='certificati_created_1bef78_idx'),
        ),
    ]
