# Generated by Django 5.0.6 on 2026-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_certificate_certificati_learner_94611f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='digital_signature',
            field=models.CharField(blank=True, db_index=True, help_text='HMAC-SHA256 digital signature verifying authenticity', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic file integrity checksum', max_length=64, null=True),
        ),
    ]
