# Generated by Django 5.0.6 on 2026-07-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_remove_course_is_published_course_course_status_and_more'),
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclasswork',
            name='classwork_file',
            field=models.FileField(blank=True, null=True, upload_to='classwork_files/'),
        ),
        migrations.AddField(
            model_name='trainingclasswork',
            name='linked_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_training_classworks', to='Course.quizes'),
        ),
        migrations.AddField(
            model_name='trainingfinalexam',
            name='linked_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_training_exams', to='Course.quizes'),
        ),
        migrations.AlterField(
            model_name='trainingclasswork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingfinalexam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
