# Generated by Django 5.0.6 on 2026-07-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0002_trainingclasswork_classwork_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfinalexam',
            name='exam_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_files/'),
        ),
    ]
