# Generated by Django 5.0.6 on 2026-07-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_instructor_can_create_courses_and_more'),
        ('Training', '0003_trainingfinalexam_exam_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='Auth.instructor'),
        ),
    ]
