# Generated by Django 5.0.6 on 2026-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0004_training_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclassworksubmission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trainingclassworksubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='classwork_submissions/'),
        ),
    ]
