# Generated by Django 5.0.6 on 2026-07-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0005_trainingclassworksubmission_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='application_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='application_open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingparticipants',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainingparticipants',
            name='application_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingparticipants',
            name='application_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
