# Generated by Django 5.0.6 on 2026-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0006_training_application_close_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('training_type', models.CharField(choices=[('Professional Training', 'Professional Training'), ('Academic Internship', 'Academic Internship'), ('Other', 'Other')], max_length=50)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('learning_fields', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
