# Generated by Django 5.0.6 on 2026-07-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0008_training_auto_issue_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingparticipants',
            name='admission_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ADMITTED', 'Admitted'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
