# Generated by Django 5.0.6 on 2026-07-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0010_training_certificate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='passing_score_percentage',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Percentage required to automatically pass and receive the certificate (0-100).', max_digits=5),
        ),
    ]
