# Generated by Django 5.0.6 on 2026-08-03 12:28

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0011_training_passing_score_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingclasswork',
            name='classwork_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='classwork_files/'),
        ),
        migrations.AlterField(
            model_name='trainingclassworksubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='classwork_submissions/'),
        ),
        migrations.AlterField(
            model_name='trainingfinalexam',
            name='exam_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='exam_files/'),
        ),
        migrations.AlterField(
            model_name='trainingfinalexamsubmission',
            name='submission_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='exam_submissions/'),
        ),
    ]
