# Generated by Django 5.0.6 on 2026-08-03 13:34

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0012_alter_trainingclasswork_classwork_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfinalexamsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingfinalexamsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='media/exam_submissions/'),
        ),
    ]
