# Generated by Django 5.0.6 on 2026-08-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0013_trainingfinalexamsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfinalexam',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
