# Generated by Django 5.0.6 on 2026-08-05 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_user_options_alter_user_user_type_and_more'),
        ('Training', '0015_trainingmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='trainingparticipants',
            options={'ordering': ['-date_applied']},
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['instructor', '-date_created'], name='Training_tr_instruc_9cf813_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingparticipants',
            index=models.Index(fields=['training', 'admission_status'], name='Training_tr_trainin_576441_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingparticipants',
            index=models.Index(fields=['participant', 'admission_status'], name='Training_tr_partici_72dc18_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingparticipants',
            index=models.Index(fields=['admission_status', '-date_applied'], name='Training_tr_admissi_f6cd30_idx'),
        ),
    ]
