# Generated by Django 5.0.6 on 2026-08-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0016_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclasswork',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic file integrity checksum', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='trainingclassworksubmission',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic file integrity checksum', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='trainingfinalexam',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic file integrity checksum', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='trainingfinalexamsubmission',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 cryptographic file integrity checksum', max_length=64, null=True),
        ),
    ]
