# Generated by Django 5.0.6 on 2026-08-06 09:21

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Training = apps.get_model('Training', 'Training')
    for training in Training.objects.all():
        if not training.slug:
            base_slug = slugify(training.title or f"training-{training.pk}")
            slug = base_slug
            counter = 1
            while Training.objects.filter(slug=slug).exclude(pk=training.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            training.slug = slug
            training.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0017_trainingclasswork_sha256_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, db_index=False),
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, default=''),
            preserve_default=False,
        ),
    ]
